### ISSUE TITLE
Change default RuboCop multiline style to `indented`

### ISSUE THREAD

**Issue by florish** [brightin/styleguide#6]
I get RuboCop warnings quite often for multiline operations. Code example:

```ruby
some_variable = Model
  .where(foo: 'bar')
  .order(..)
  .first
```

RuboCop then gives me a `Style/MultilineOperationIndentation` error:
```
path/to/file.rb:11:22: C: Align the operands of an expression in an assignment spanning multiple lines.
      .where(foo: 'bar')
      ^^^^^^
```

In [this comment](https://github.com/bbatsov/rubocop/issues/1633#issuecomment-73067109) I see there are two multiline styles: `aligned` and `indented`. 

RuboCop defaults to `aligned`, but I personally prefer the `indented` style, as it avoids having to reindent consecutive lines if the left hand side of the first line is changed. I like to avoid manually formatting code indenting as much as possible.

Would you consider updating the style guide with `indented` as a default?

**Comment by avdgaag** [comment]
> I like to avoid manually formatting code indenting as much as possible.

Your editor should do this for you, so one should not be more work than the other — it's purely aesthetic. That said, `aligned` can be hard to read given long lines. I'd take a PR for this change!
